# -*- coding: utf-8 -*-
"""thesis_coding_0423.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jxqWQ2yLfPcq6pdn1OoaDNWMlVhFrkYq
"""

"""Full corrected analysis — proper AIREG coding, all H1/H2/H3 models."""
import pandas as pd
import numpy as np
from scipy import stats
import statsmodels.api as sm
from statsmodels.miscmodels.ordinal_model import OrderedModel
import warnings
warnings.filterwarnings('ignore')

pd.set_option('display.max_columns', 50)
pd.set_option('display.width', 200)

print("✅ All packages loaded.")

from google.colab import files
print("📁 Upload your ATP_W152.csv file...")
uploaded = files.upload()
filename = list(uploaded.keys())[0]
df = pd.read_csv(filename, low_memory=False)
print(f"✅ Loaded {filename}: {df.shape[0]:,} rows × {df.shape[1]} columns")

# === AI Concern Index ===
concern_items = [f'AICONCERN_{x}_W152' for x in 'abcdefg']
for col in concern_items:
    df[col] = df[col].replace(99, np.nan)
    df[col + '_r'] = 6 - df[col]
df['AI_CONCERN_INDEX'] = df[[c + '_r' for c in concern_items]].mean(axis=1)

item_data = df[[c + '_r' for c in concern_items]].dropna()
k = 7
alpha = (k / (k - 1)) * (1 - item_data.var().sum() / item_data.sum(axis=1).var())
print(f"Cronbach's alpha = {alpha:.4f}")

# === DV1: AIREG — CORRECTED coding ===
# Pew raw: 1 = Go too far, 2 = Not far enough, 3 = Not sure
# Correct recode: 1 → 1 (anti-reg), 3 → 2 (middle/uncertain), 2 → 3 (pro-reg)
df['AIREG'] = df['AIREG_W152'].replace(99, np.nan)
df['AIREG'] = df['AIREG'].map({1.0: 1.0, 2.0: 3.0, 3.0: 2.0})
print("\nAIREG corrected distribution:")
print(df['AIREG'].value_counts().sort_index())

# === DV2: REGCONFG ===
# Pew raw: 1 great deal, 2 quite a bit, 3 some, 4 not too much, 5 none, 6 not sure
df['REGCONFG'] = df['REGCONFG_W152'].replace(99, np.nan)
df.loc[df['REGCONFG'] == 6, 'REGCONFG'] = np.nan   # drop "not sure"
# Reverse: 1 (none) → 1, 5 (great deal) → 5
df['REGCONFG'] = 6 - df['REGCONFG']
print("\nREGCONFG corrected distribution (1=none … 5=great deal):")
print(df['REGCONFG'].value_counts().sort_index())

# === Ideology + controls ===
df['IDEOLOGY'] = df['F_IDEO'].replace(99, np.nan)
df['CONSERVATIVE'] = 6 - df['IDEOLOGY']
df['AGE_CAT'] = df['F_AGECAT'].replace(99, np.nan)
df['FEMALE'] = (df['F_GENDER'] == 2).astype(float)
df.loc[df['F_GENDER'] == 99, 'FEMALE'] = np.nan
df['COLLEGE'] = (df['F_EDUCCAT'] == 1).astype(float)
df.loc[df['F_EDUCCAT'] == 99, 'COLLEGE'] = np.nan
df['INCOME_TIER'] = df['F_INC_TIER2'].replace(99, np.nan)
df['WHITE'] = (df['F_RACETHNMOD'] == 1).astype(float)
df.loc[df['F_RACETHNMOD'] == 99, 'WHITE'] = np.nan
df['WT'] = df['WEIGHT_W152']

controls = ['IDEOLOGY', 'AGE_CAT', 'FEMALE', 'COLLEGE', 'INCOME_TIER', 'WHITE']

# === Summary stats ===
print("\n" + "="*90)
print("TABLE 1: SUMMARY STATISTICS")
print("="*90)
summary_vars = [
    ('AI_CONCERN_INDEX', 'AI Concern Index', '1–5'),
    ('AIREG',            'Support for Regulation', '1–3'),
    ('REGCONFG',         'Confidence in Gov Regulation', '1–5'),
    ('IDEOLOGY',         'Ideology (liberal higher)', '1–5'),
    ('AGE_CAT',          'Age Category', '1–4'),
    ('FEMALE',           'Female', '0/1'),
    ('COLLEGE',          'College Graduate', '0/1'),
    ('INCOME_TIER',      'Income Tier', '1–3'),
    ('WHITE',            'White Non-Hispanic', '0/1'),
]
rows = []
for var, label, rng in summary_vars:
    col = df[var].dropna()
    rows.append({'Variable': label, 'Range': rng, 'N': int(col.count()),
                 'Mean': round(col.mean(), 3), 'SD': round(col.std(), 3),
                 'Min': col.min(), 'Max': col.max()})
summary = pd.DataFrame(rows)
print(summary.to_string(index=False))

# === H1 ===
print("\n" + "="*90)
print("H1: AI Concern → Support for Regulation (AIREG)")
print("="*90)
h1 = df[['AIREG', 'AI_CONCERN_INDEX'] + controls + ['WT']].dropna()

m1_h1 = sm.WLS(h1['AIREG'], sm.add_constant(h1[['AI_CONCERN_INDEX']]),
               weights=h1['WT']).fit(cov_type='HC1')
print("\n--- Model 1 (bivariate) ---")
print(m1_h1.summary().tables[1])
print(f"N = {int(m1_h1.nobs)}, R² = {m1_h1.rsquared:.4f}")

m2_h1 = sm.WLS(h1['AIREG'], sm.add_constant(h1[['AI_CONCERN_INDEX'] + controls]),
               weights=h1['WT']).fit(cov_type='HC1')
print("\n--- Model 2 (with controls) ---")
print(m2_h1.summary().tables[1])
print(f"N = {int(m2_h1.nobs)}, R² = {m2_h1.rsquared:.4f}")

# === H2 ===
print("\n" + "="*90)
print("H2: AI Concern → Confidence in Government Regulation (REGCONFG)")
print("="*90)
h2 = df[['REGCONFG', 'AI_CONCERN_INDEX'] + controls + ['WT']].dropna()

m1_h2 = sm.WLS(h2['REGCONFG'], sm.add_constant(h2[['AI_CONCERN_INDEX']]),
               weights=h2['WT']).fit(cov_type='HC1')
print("\n--- Model 1 (bivariate) ---")
print(m1_h2.summary().tables[1])
print(f"N = {int(m1_h2.nobs)}, R² = {m1_h2.rsquared:.4f}")

m2_h2 = sm.WLS(h2['REGCONFG'], sm.add_constant(h2[['AI_CONCERN_INDEX'] + controls]),
               weights=h2['WT']).fit(cov_type='HC1')
print("\n--- Model 2 (with controls) ---")
print(m2_h2.summary().tables[1])
print(f"N = {int(m2_h2.nobs)}, R² = {m2_h2.rsquared:.4f}")

# === H3a: Ideology moderates H1 ===
print("\n" + "="*90)
print("H3a: Ideology moderates H1 (AIREG)")
print("="*90)
h3a = df[['AIREG', 'AI_CONCERN_INDEX', 'CONSERVATIVE', 'AGE_CAT', 'FEMALE',
         'COLLEGE', 'INCOME_TIER', 'WHITE', 'WT']].dropna()
h3a['CONCERN_x_CONSERV'] = h3a['AI_CONCERN_INDEX'] * h3a['CONSERVATIVE']
m_h3a = sm.WLS(h3a['AIREG'],
               sm.add_constant(h3a[['AI_CONCERN_INDEX', 'CONSERVATIVE', 'CONCERN_x_CONSERV',
                                     'AGE_CAT', 'FEMALE', 'COLLEGE', 'INCOME_TIER', 'WHITE']]),
               weights=h3a['WT']).fit(cov_type='HC1')
print(m_h3a.summary().tables[1])
print(f"N = {int(m_h3a.nobs)}, R² = {m_h3a.rsquared:.4f}")

# === H3b: Ideology moderates H2 ===
print("\n" + "="*90)
print("H3b: Ideology moderates H2 (REGCONFG)")
print("="*90)
h3b = df[['REGCONFG', 'AI_CONCERN_INDEX', 'CONSERVATIVE', 'AGE_CAT', 'FEMALE',
          'COLLEGE', 'INCOME_TIER', 'WHITE', 'WT']].dropna()
h3b['CONCERN_x_CONSERV'] = h3b['AI_CONCERN_INDEX'] * h3b['CONSERVATIVE']
m_h3b = sm.WLS(h3b['REGCONFG'],
               sm.add_constant(h3b[['AI_CONCERN_INDEX', 'CONSERVATIVE', 'CONCERN_x_CONSERV',
                                     'AGE_CAT', 'FEMALE', 'COLLEGE', 'INCOME_TIER', 'WHITE']]),
               weights=h3b['WT']).fit(cov_type='HC1')
print(m_h3b.summary().tables[1])
print(f"N = {int(m_h3b.nobs)}, R² = {m_h3b.rsquared:.4f}")

# === Robustness: Ordered Logit ===
print("\n" + "="*90)
print("ROBUSTNESS: Ordered Logit")
print("="*90)
h1_ol = df[['AIREG', 'AI_CONCERN_INDEX'] + controls].dropna()
ologit_h1 = OrderedModel(h1_ol['AIREG'], h1_ol[['AI_CONCERN_INDEX'] + controls],
                         distr='logit').fit(method='bfgs', disp=False)
print(f"\nH1 ordered logit — AI_CONCERN_INDEX: "
      f"coef = {ologit_h1.params['AI_CONCERN_INDEX']:.4f}, "
      f"SE = {ologit_h1.bse['AI_CONCERN_INDEX']:.4f}, "
      f"p = {ologit_h1.pvalues['AI_CONCERN_INDEX']:.4f}")

h2_ol = df[['REGCONFG', 'AI_CONCERN_INDEX'] + controls].dropna()
ologit_h2 = OrderedModel(h2_ol['REGCONFG'], h2_ol[['AI_CONCERN_INDEX'] + controls],
                         distr='logit').fit(method='bfgs', disp=False)
print(f"\nH2 ordered logit — AI_CONCERN_INDEX: "
      f"coef = {ologit_h2.params['AI_CONCERN_INDEX']:.4f}, "
      f"SE = {ologit_h2.bse['AI_CONCERN_INDEX']:.4f}, "
      f"p = {ologit_h2.pvalues['AI_CONCERN_INDEX']:.4f}")

# === Descriptive breakdowns for writeup ===
print("\n" + "="*90)
print("DESCRIPTIVES BY IDEOLOGY (weighted)")
print("="*90)
sub = df[['AIREG', 'IDEOLOGY', 'WT']].dropna()
sub['group'] = pd.cut(sub['IDEOLOGY'], bins=[0, 2, 3, 5], labels=['Conservative', 'Moderate', 'Liberal'])
print("\nAIREG (regulation support) by ideology — weighted %")
print("  1 = Go too far, 2 = Not sure, 3 = Not far enough")
for g in ['Conservative', 'Moderate', 'Liberal']:
    s = sub[sub['group'] == g]
    tot = s['WT'].sum()
    vals = {v: s[s['AIREG'] == v]['WT'].sum() / tot * 100 for v in [1.0, 2.0, 3.0]}
    print(f"  {g:15} too far={vals[1.0]:5.1f}%  not sure={vals[2.0]:5.1f}%  not far enough={vals[3.0]:5.1f}%")

sub = df[['REGCONFG', 'IDEOLOGY', 'WT']].dropna()
sub['group'] = pd.cut(sub['IDEOLOGY'], bins=[0, 2, 3, 5], labels=['Conservative', 'Moderate', 'Liberal'])
print("\nREGCONFG (confidence in gov regulation) by ideology — weighted %")
print("  Low confidence = 'None' or 'Not too much' (values 1 or 2)")
for g in ['Conservative', 'Moderate', 'Liberal']:
    s = sub[sub['group'] == g]
    tot = s['WT'].sum()
    low = s[s['REGCONFG'] <= 2]['WT'].sum() / tot * 100
    print(f"  {g:15} low confidence = {low:.1f}%")

sub = df[['AIREG', 'IDEOLOGY', 'WT']].dropna()

for name, lo, hi in [('Conservative', 1, 2), ('Moderate', 3, 3), ('Liberal', 4, 5)]:
    group = sub[sub['IDEOLOGY'].between(lo, hi)]
    total_wt = group['WT'].sum()
    nfe_wt = group[group['AIREG'] == 3]['WT'].sum()
    pct = nfe_wt / total_wt * 100
    print(f"{name}: not far enough = {pct:.1f}%")
    print(f"  numerator (AIREG=3 weights sum) = {nfe_wt:.2f}")
    print(f"  denominator (all weights sum) = {total_wt:.2f}")

# Overall means
print("\nConcern index mean by ideology (weighted)")
sub = df[['AI_CONCERN_INDEX', 'IDEOLOGY', 'WT']].dropna()
sub['group'] = pd.cut(sub['IDEOLOGY'], bins=[0, 2, 3, 5], labels=['Conservative', 'Moderate', 'Liberal'])
for g in ['Conservative', 'Moderate', 'Liberal']:
    s = sub[sub['group'] == g]
    wm = (s['AI_CONCERN_INDEX'] * s['WT']).sum() / s['WT'].sum()
    print(f"  {g:15} mean = {wm:.3f}")

print("\nDONE.")

print("\n" + "="*90)
print("TABLE A.1: WLS with CLASSIC (non-robust) SEs")
print("="*90)

# H1
m1_h1_nr = sm.WLS(h1['AIREG'], sm.add_constant(h1[['AI_CONCERN_INDEX']]),
                  weights=h1['WT']).fit()
m2_h1_nr = sm.WLS(h1['AIREG'], sm.add_constant(h1[['AI_CONCERN_INDEX'] + controls]),
                  weights=h1['WT']).fit()

print("\nH1 Model 1 (no robust SE):")
print(m1_h1_nr.summary().tables[1])

print("\nH1 Model 2 (no robust SE):")
print(m2_h1_nr.summary().tables[1])

# H2
m1_h2_nr = sm.WLS(h2['REGCONFG'], sm.add_constant(h2[['AI_CONCERN_INDEX']]),
                  weights=h2['WT']).fit()
m2_h2_nr = sm.WLS(h2['REGCONFG'], sm.add_constant(h2[['AI_CONCERN_INDEX'] + controls]),
                  weights=h2['WT']).fit()

print("\nH2 Model 1 (no robust SE):")
print(m1_h2_nr.summary().tables[1])

print("\nH2 Model 2 (no robust SE):")
print(m2_h2_nr.summary().tables[1])

print("\n" + "="*90)
print("TABLE A.2: FULL ORDERED LOGIT RESULTS")
print("="*90)

print("\nH1 Ordered Logit:")
print(ologit_h1.summary())

print("\nH2 Ordered Logit:")
print(ologit_h2.summary())

print("\n" + "="*90)
print("TABLE A.3: UNWEIGHTED OLS")
print("="*90)

# H1
m1_h1_ols = sm.OLS(h1['AIREG'], sm.add_constant(h1[['AI_CONCERN_INDEX']])).fit(cov_type='HC1')
m2_h1_ols = sm.OLS(h1['AIREG'], sm.add_constant(h1[['AI_CONCERN_INDEX'] + controls])).fit(cov_type='HC1')

print("\nH1 Model 1 (OLS):")
print(m1_h1_ols.summary().tables[1])

print("\nH1 Model 2 (OLS):")
print(m2_h1_ols.summary().tables[1])

# H2
m1_h2_ols = sm.OLS(h2['REGCONFG'], sm.add_constant(h2[['AI_CONCERN_INDEX']])).fit(cov_type='HC1')
m2_h2_ols = sm.OLS(h2['REGCONFG'], sm.add_constant(h2[['AI_CONCERN_INDEX'] + controls])).fit(cov_type='HC1')

print("\nH2 Model 1 (OLS):")
print(m1_h2_ols.summary().tables[1])

print("\nH2 Model 2 (OLS):")
print(m2_h2_ols.summary().tables[1])

print("\n" + "="*90)
print("TABLE A.4: SAMPLE DEMOGRAPHICS BY IDEOLOGY")
print("="*90)

demo = df[['IDEOLOGY','AGE_CAT','FEMALE','COLLEGE','INCOME_TIER','WHITE','WT']].dropna()
demo['group'] = pd.cut(demo['IDEOLOGY'], bins=[0,2,3,5],
                       labels=['Conservative','Moderate','Liberal'])

def wmean(x, w):
    return (x * w).sum() / w.sum()

rows = []
for g in ['Conservative','Moderate','Liberal']:
    sub = demo[demo['group'] == g]
    w = sub['WT']
    rows.append({
        'Group': g,
        'N': len(sub),
        'Age (mean)': wmean(sub['AGE_CAT'], w),
        'Female (%)': wmean(sub['FEMALE'], w)*100,
        'College (%)': wmean(sub['COLLEGE'], w)*100,
        'Income (mean)': wmean(sub['INCOME_TIER'], w),
        'White (%)': wmean(sub['WHITE'], w)*100
    })

table_a4 = pd.DataFrame(rows)
print(table_a4.round(3).to_string(index=False))

print("\n" + "="*90)
print("TABLE A.5: AI CONCERN INDEX ITEM STATISTICS")
print("="*90)

items = [c + '_r' for c in concern_items]
item_df = df[items].dropna()

rows = []
total = item_df.sum(axis=1)

for col in items:
    corr = np.corrcoef(item_df[col], total)[0,1]
    rows.append({
        'Item': col,
        'Mean': item_df[col].mean(),
        'SD': item_df[col].std(),
        'Item-total corr': corr
    })

table_a5 = pd.DataFrame(rows)
print(table_a5.round(3).to_string(index=False))

print("\n" + "="*90)
print("TABLE A.6: FULL CROSS-TABULATIONS (WEIGHTED %)")
print("="*90)

def weighted_crosstab(df, row, col, weight):
    categories_row = sorted(df[row].dropna().unique())
    categories_col = df[col].cat.categories

    table = pd.DataFrame(index=categories_row, columns=categories_col)

    for c in categories_col:
        sub = df[df[col] == c]
        total_w = sub[weight].sum()
        for r in categories_row:
            val = sub[sub[row] == r][weight].sum()
            table.loc[r, c] = (val / total_w * 100) if total_w > 0 else np.nan

    return table.astype(float)

# Prepare ideology groups
df_ct = df[['AIREG','REGCONFG','IDEOLOGY','WT']].dropna()
df_ct['group'] = pd.cut(df_ct['IDEOLOGY'], bins=[0,2,3,5],
                        labels=['Conservative','Moderate','Liberal'])

# AIREG × ideology
print("\nAIREG × Ideology (% within ideology)")
aireg_tab = weighted_crosstab(df_ct, 'AIREG', 'group', 'WT')
print(aireg_tab.round(2))

# REGCONFG × ideology
print("\nREGCONFG × Ideology (% within ideology)")
regconf_tab = weighted_crosstab(df_ct, 'REGCONFG', 'group', 'WT')
print(regconf_tab.round(2))

def export_regression_to_excel(model, filename):
    table = model.summary2().tables[1]
    table.to_excel(filename)

# H1
export_regression_to_excel(m1_h1_nr, "A1_H1_model1.xlsx")
export_regression_to_excel(m2_h1_nr, "A1_H1_model2.xlsx")

# H2
export_regression_to_excel(m1_h2_nr, "A1_H2_model1.xlsx")
export_regression_to_excel(m2_h2_nr, "A1_H2_model2.xlsx")

def export_ologit_to_excel(model, filename):
    df_out = pd.DataFrame({
        'coef': model.params,
        'std_err': model.bse,
        'p_value': model.pvalues
    })
    df_out.to_excel(filename)

export_ologit_to_excel(ologit_h1, "A2_H1_ordered_logit.xlsx")
export_ologit_to_excel(ologit_h2, "A2_H2_ordered_logit.xlsx")

# H1
export_regression_to_excel(m1_h1_ols, "A3_H1_model1_OLS.xlsx")
export_regression_to_excel(m2_h1_ols, "A3_H1_model2_OLS.xlsx")

# H2
export_regression_to_excel(m1_h2_ols, "A3_H2_model1_OLS.xlsx")
export_regression_to_excel(m2_h2_ols, "A3_H2_model2_OLS.xlsx")

table_a4.to_excel("A4_demographics_by_ideology.xlsx", index=False)

table_a5.to_excel("A5_AI_concern_items.xlsx", index=False)

aireg_tab.to_excel("A6_AIREG_by_ideology.xlsx")
regconf_tab.to_excel("A6_REGCONFG_by_ideology.xlsx")

# =====================================================================
# PATCH: Add H3a & H3b to Appendix Tables A.1, A.2, A.3 + Export
# Paste this cell at the end of your notebook (after Cell 19)
# =====================================================================

# Make sure h3a, h3b dataframes exist (from Cells 8 & 9)
# If you get a NameError, re-run Cells 8 and 9 first.

print("=" * 90)
print("PATCH: Adding H3a & H3b to Appendix Tables")
print("=" * 90)

# --- A.1 SUPPLEMENT: H3a & H3b with classic (non-robust) SEs ---
print("\n" + "=" * 90)
print("TABLE A.1 SUPPLEMENT: H3a & H3b with CLASSIC (non-robust) SEs")
print("=" * 90)

m_h3a_nr = sm.WLS(h3a['AIREG'],
    sm.add_constant(h3a[['AI_CONCERN_INDEX', 'CONSERVATIVE', 'CONCERN_x_CONSERV',
                          'AGE_CAT', 'FEMALE', 'COLLEGE', 'INCOME_TIER', 'WHITE']]),
    weights=h3a['WT']).fit()

m_h3b_nr = sm.WLS(h3b['REGCONFG'],
    sm.add_constant(h3b[['AI_CONCERN_INDEX', 'CONSERVATIVE', 'CONCERN_x_CONSERV',
                          'AGE_CAT', 'FEMALE', 'COLLEGE', 'INCOME_TIER', 'WHITE']]),
    weights=h3b['WT']).fit()

print("\nH3a (non-robust SE):")
print(m_h3a_nr.summary().tables[1])
print(f"N = {int(m_h3a_nr.nobs)}, R² = {m_h3a_nr.rsquared:.4f}")

print("\nH3b (non-robust SE):")
print(m_h3b_nr.summary().tables[1])
print(f"N = {int(m_h3b_nr.nobs)}, R² = {m_h3b_nr.rsquared:.4f}")


# --- A.2 SUPPLEMENT: H3a & H3b ordered logit ---
print("\n" + "=" * 90)
print("TABLE A.2 SUPPLEMENT: H3a & H3b Ordered Logit")
print("=" * 90)

from statsmodels.miscmodels.ordinal_model import OrderedModel

# H3a ordered logit
h3a_ol = df[['AIREG', 'AI_CONCERN_INDEX', 'CONSERVATIVE'] +
            ['AGE_CAT', 'FEMALE', 'COLLEGE', 'INCOME_TIER', 'WHITE']].dropna()
h3a_ol['CONCERN_x_CONSERV'] = h3a_ol['AI_CONCERN_INDEX'] * h3a_ol['CONSERVATIVE']

try:
    ologit_h3a = OrderedModel(
        h3a_ol['AIREG'],
        h3a_ol[['AI_CONCERN_INDEX', 'CONSERVATIVE', 'CONCERN_x_CONSERV',
                 'AGE_CAT', 'FEMALE', 'COLLEGE', 'INCOME_TIER', 'WHITE']],
        distr='logit').fit(method='bfgs', disp=False)
    print("\nH3a Ordered Logit:")
    print(f"  CONCERN_x_CONSERV: coef = {ologit_h3a.params['CONCERN_x_CONSERV']:.4f}, "
          f"SE = {ologit_h3a.bse['CONCERN_x_CONSERV']:.4f}, "
          f"p = {ologit_h3a.pvalues['CONCERN_x_CONSERV']:.4f}")
    print(ologit_h3a.summary().tables[1])
except Exception as e:
    print(f"  H3a ordered logit failed: {e}")
    ologit_h3a = None

# H3b ordered logit
h3b_ol = df[['REGCONFG', 'AI_CONCERN_INDEX', 'CONSERVATIVE'] +
            ['AGE_CAT', 'FEMALE', 'COLLEGE', 'INCOME_TIER', 'WHITE']].dropna()
h3b_ol['CONCERN_x_CONSERV'] = h3b_ol['AI_CONCERN_INDEX'] * h3b_ol['CONSERVATIVE']

try:
    ologit_h3b = OrderedModel(
        h3b_ol['REGCONFG'],
        h3b_ol[['AI_CONCERN_INDEX', 'CONSERVATIVE', 'CONCERN_x_CONSERV',
                 'AGE_CAT', 'FEMALE', 'COLLEGE', 'INCOME_TIER', 'WHITE']],
        distr='logit').fit(method='bfgs', disp=False)
    print("\nH3b Ordered Logit:")
    print(f"  CONCERN_x_CONSERV: coef = {ologit_h3b.params['CONCERN_x_CONSERV']:.4f}, "
          f"SE = {ologit_h3b.bse['CONCERN_x_CONSERV']:.4f}, "
          f"p = {ologit_h3b.pvalues['CONCERN_x_CONSERV']:.4f}")
    print(ologit_h3b.summary().tables[1])
except Exception as e:
    print(f"  H3b ordered logit failed: {e}")
    ologit_h3b = None


# --- A.3 SUPPLEMENT: H3a & H3b unweighted OLS ---
print("\n" + "=" * 90)
print("TABLE A.3 SUPPLEMENT: H3a & H3b Unweighted OLS")
print("=" * 90)

m_h3a_ols = sm.OLS(h3a['AIREG'],
    sm.add_constant(h3a[['AI_CONCERN_INDEX', 'CONSERVATIVE', 'CONCERN_x_CONSERV',
                          'AGE_CAT', 'FEMALE', 'COLLEGE', 'INCOME_TIER', 'WHITE']])
).fit(cov_type='HC1')

m_h3b_ols = sm.OLS(h3b['REGCONFG'],
    sm.add_constant(h3b[['AI_CONCERN_INDEX', 'CONSERVATIVE', 'CONCERN_x_CONSERV',
                          'AGE_CAT', 'FEMALE', 'COLLEGE', 'INCOME_TIER', 'WHITE']])
).fit(cov_type='HC1')

print("\nH3a (unweighted OLS):")
print(m_h3a_ols.summary().tables[1])
print(f"N = {int(m_h3a_ols.nobs)}, R² = {m_h3a_ols.rsquared:.4f}")

print("\nH3b (unweighted OLS):")
print(m_h3b_ols.summary().tables[1])
print(f"N = {int(m_h3b_ols.nobs)}, R² = {m_h3b_ols.rsquared:.4f}")


# --- EXPORT ALL H3 supplements ---
print("\n" + "=" * 90)
print("EXPORTING H3a & H3b supplements")
print("=" * 90)

# A.1: non-robust SEs
export_regression_to_excel(m_h3a_nr, "A1_H3a_non_robust.xlsx")
export_regression_to_excel(m_h3b_nr, "A1_H3b_non_robust.xlsx")

# A.2: ordered logit
if ologit_h3a is not None:
    export_ologit_to_excel(ologit_h3a, "A2_H3a_ordered_logit.xlsx")
if ologit_h3b is not None:
    export_ologit_to_excel(ologit_h3b, "A2_H3b_ordered_logit.xlsx")

# A.3: unweighted OLS
export_regression_to_excel(m_h3a_ols, "A3_H3a_OLS.xlsx")
export_regression_to_excel(m_h3b_ols, "A3_H3b_OLS.xlsx")

print("\n✅ All H3a & H3b supplements exported.")
print("Files: A1_H3a/b_non_robust.xlsx, A2_H3a/b_ordered_logit.xlsx, A3_H3a/b_OLS.xlsx")

# === CORRELATION TABLE ===
corr_vars = ['AI_CONCERN_INDEX', 'AIREG', 'REGCONFG', 'IDEOLOGY',
             'AGE_CAT', 'FEMALE', 'COLLEGE', 'INCOME_TIER', 'WHITE']

corr_df = df[corr_vars].dropna()
corr_matrix = corr_df.corr().round(3)

print("=" * 90)
print("TABLE X: Correlation Matrix")
print("=" * 90)
print(corr_matrix.to_string())

# Export
corr_matrix.to_excel("correlation_table.xlsx")
print("\n✅ Exported: correlation_table.xlsx")

"""
Consolidated Appendix Tables for Thesis
=========================================
Run this AFTER your existing notebook cells (specifically after Cell 9 which
creates h1, h2, h3a, h3b dataframes and the OrderedModel imports).

This script regenerates all four appendix tables (A.1, A.2, A.3) as single
combined tables matching the structure used in the Word document.

Each combined table includes:
- A.1 (WLS classic SEs):    H1 M1, H1 M2, H2 M1, H2 M2, H3a, H3b
- A.2 (Ordered Logit):      H1,    H2,    H3a, H3b
- A.3 (Unweighted OLS HC1): H1 M1, H1 M2, H2 M1, H2 M2, H3a, H3b
- A.4 (Sample demographics by ideology)
- A.5 (AI Concern Index item statistics)
"""

import pandas as pd
import numpy as np
import statsmodels.api as sm
from statsmodels.miscmodels.ordinal_model import OrderedModel

# ============================================================
# ASSUMPTIONS
# ============================================================
# This script assumes the following objects already exist in your namespace,
# created by your earlier notebook cells:
#
#   df              - full dataframe with all recoded variables
#   controls        - list of control variable names: ['IDEOLOGY', 'AGE_CAT',
#                     'FEMALE', 'COLLEGE', 'INCOME_TIER', 'WHITE']
#   h1              - dataframe filtered for H1 (with AIREG + concern + controls + WT)
#   h2              - dataframe filtered for H2 (with REGCONFG + concern + controls + WT)
#   h3a             - dataframe for H3a (with CONCERN_x_CONSERV column added)
#   h3b             - dataframe for H3b
#   concern_items   - list of seven AICONCERN item names
#
# If you get NameError, re-run cells 0 through 9 first.

# ============================================================
# SIGNIFICANCE STAR HELPER
# ============================================================
def stars(p):
    if p < 0.01:
        return '***'
    elif p < 0.05:
        return '**'
    elif p < 0.10:
        return '*'
    return ''


def fmt_coef(coef, p):
    """Format coefficient with significance stars."""
    return f"{coef:.3f}{stars(p)}"


def fmt_se(se):
    """Format standard error in parentheses."""
    return f"({se:.3f})"


def extract_row(model, var_name):
    """Extract coefficient and SE for a variable from a fitted model. Returns (coef_str, se_str)."""
    if var_name not in model.params.index:
        return ("", "")
    coef = model.params[var_name]
    se = model.bse[var_name]
    p = model.pvalues[var_name]
    return (fmt_coef(coef, p), fmt_se(se))


# ============================================================
# RE-RUN ALL MODELS (so we know the numbers come from a single run)
# ============================================================
print("=" * 90)
print("RUNNING ALL APPENDIX MODELS")
print("=" * 90)

# --- A.1: WLS with classic (non-robust) SEs ---
m1_h1_nr = sm.WLS(h1['AIREG'],
                  sm.add_constant(h1[['AI_CONCERN_INDEX']]),
                  weights=h1['WT']).fit()
m2_h1_nr = sm.WLS(h1['AIREG'],
                  sm.add_constant(h1[['AI_CONCERN_INDEX'] + controls]),
                  weights=h1['WT']).fit()
m1_h2_nr = sm.WLS(h2['REGCONFG'],
                  sm.add_constant(h2[['AI_CONCERN_INDEX']]),
                  weights=h2['WT']).fit()
m2_h2_nr = sm.WLS(h2['REGCONFG'],
                  sm.add_constant(h2[['AI_CONCERN_INDEX'] + controls]),
                  weights=h2['WT']).fit()

# H3a, H3b WLS (classic SEs)
h3_controls = ['AI_CONCERN_INDEX', 'CONSERVATIVE', 'CONCERN_x_CONSERV',
               'AGE_CAT', 'FEMALE', 'COLLEGE', 'INCOME_TIER', 'WHITE']
m_h3a_nr = sm.WLS(h3a['AIREG'],
                  sm.add_constant(h3a[h3_controls]),
                  weights=h3a['WT']).fit()
m_h3b_nr = sm.WLS(h3b['REGCONFG'],
                  sm.add_constant(h3b[h3_controls]),
                  weights=h3b['WT']).fit()

# --- A.2: Ordered Logit ---
h1_ol = df[['AIREG', 'AI_CONCERN_INDEX'] + controls].dropna()
h2_ol = df[['REGCONFG', 'AI_CONCERN_INDEX'] + controls].dropna()

ologit_h1 = OrderedModel(h1_ol['AIREG'],
                         h1_ol[['AI_CONCERN_INDEX'] + controls],
                         distr='logit').fit(method='bfgs', disp=False)
ologit_h2 = OrderedModel(h2_ol['REGCONFG'],
                         h2_ol[['AI_CONCERN_INDEX'] + controls],
                         distr='logit').fit(method='bfgs', disp=False)

# H3 ordered logit
h3a_ol_data = df[['AIREG', 'AI_CONCERN_INDEX', 'CONSERVATIVE',
                  'AGE_CAT', 'FEMALE', 'COLLEGE', 'INCOME_TIER', 'WHITE']].dropna()
h3a_ol_data['CONCERN_x_CONSERV'] = h3a_ol_data['AI_CONCERN_INDEX'] * h3a_ol_data['CONSERVATIVE']
ologit_h3a = OrderedModel(h3a_ol_data['AIREG'],
                          h3a_ol_data[h3_controls],
                          distr='logit').fit(method='bfgs', disp=False)

h3b_ol_data = df[['REGCONFG', 'AI_CONCERN_INDEX', 'CONSERVATIVE',
                  'AGE_CAT', 'FEMALE', 'COLLEGE', 'INCOME_TIER', 'WHITE']].dropna()
h3b_ol_data['CONCERN_x_CONSERV'] = h3b_ol_data['AI_CONCERN_INDEX'] * h3b_ol_data['CONSERVATIVE']
ologit_h3b = OrderedModel(h3b_ol_data['REGCONFG'],
                          h3b_ol_data[h3_controls],
                          distr='logit').fit(method='bfgs', disp=False)

# --- A.3: Unweighted OLS with HC1 SEs ---
m1_h1_ols = sm.OLS(h1['AIREG'],
                   sm.add_constant(h1[['AI_CONCERN_INDEX']])
                   ).fit(cov_type='HC1')
m2_h1_ols = sm.OLS(h1['AIREG'],
                   sm.add_constant(h1[['AI_CONCERN_INDEX'] + controls])
                   ).fit(cov_type='HC1')
m1_h2_ols = sm.OLS(h2['REGCONFG'],
                   sm.add_constant(h2[['AI_CONCERN_INDEX']])
                   ).fit(cov_type='HC1')
m2_h2_ols = sm.OLS(h2['REGCONFG'],
                   sm.add_constant(h2[['AI_CONCERN_INDEX'] + controls])
                   ).fit(cov_type='HC1')
m_h3a_ols = sm.OLS(h3a['AIREG'],
                   sm.add_constant(h3a[h3_controls])
                   ).fit(cov_type='HC1')
m_h3b_ols = sm.OLS(h3b['REGCONFG'],
                   sm.add_constant(h3b[h3_controls])
                   ).fit(cov_type='HC1')

print("All models fitted successfully.")
print()


# ============================================================
# BUILD COMBINED TABLES
# ============================================================

def build_combined_table(models, columns, var_order, footer_rows):
    """
    Build a combined regression table.

    Parameters
    ----------
    models : list of fitted models (one per column)
    columns : list of column header names
    var_order : list of (display_name, internal_name) tuples
    footer_rows : list of (label, [values]) tuples

    Returns
    -------
    pandas DataFrame with two rows per variable (coef + SE)
    """
    rows = []
    for display, internal in var_order:
        coef_row = [display]
        se_row = ['']
        for m in models:
            c, s = extract_row(m, internal)
            coef_row.append(c)
            se_row.append(s)
        rows.append(coef_row)
        rows.append(se_row)

    # Footer
    for label, values in footer_rows:
        rows.append([label] + values)

    return pd.DataFrame(rows, columns=['Variable'] + columns)


# ============================================================
# TABLE A.1: WLS with Classic (Non-Robust) SEs
# ============================================================
print("=" * 100)
print("TABLE A.1: WLS with Classic (Non-Robust) Standard Errors")
print("=" * 100)

a1_models = [m1_h1_nr, m2_h1_nr, m1_h2_nr, m2_h2_nr, m_h3a_nr, m_h3b_nr]
a1_columns = ['H1 M1', 'H1 M2', 'H2 M1', 'H2 M2', 'H3a', 'H3b']
a1_var_order = [
    ('AI Concern Index', 'AI_CONCERN_INDEX'),
    ('Ideology (liberal higher)', 'IDEOLOGY'),
    ('Conservative (1 lib – 5 cons)', 'CONSERVATIVE'),
    ('Concern × Conservative', 'CONCERN_x_CONSERV'),
    ('Age Category', 'AGE_CAT'),
    ('Female', 'FEMALE'),
    ('College Graduate', 'COLLEGE'),
    ('Income Tier', 'INCOME_TIER'),
    ('White Non-Hispanic', 'WHITE'),
    ('Constant', 'const'),
]
a1_footer = [
    ('N', [f"{int(m.nobs):,}" for m in a1_models]),
    ('R²', [f"{m.rsquared:.3f}" for m in a1_models]),
]

table_a1 = build_combined_table(a1_models, a1_columns, a1_var_order, a1_footer)
print(table_a1.to_string(index=False))
print()
print("Note: * p < 0.10, ** p < 0.05, *** p < 0.01.")
print("Classic (non-robust) standard errors in parentheses.")
print("All models apply Pew ATP Wave 152 survey weights.")
print()


# ============================================================
# TABLE A.2: Full Ordered Logit Results
# ============================================================
print("=" * 100)
print("TABLE A.2: Full Ordered Logit Results")
print("=" * 100)

a2_models = [ologit_h1, ologit_h2, ologit_h3a, ologit_h3b]
a2_columns = ['H1', 'H2', 'H3a', 'H3b']
a2_var_order = [
    ('AI Concern Index', 'AI_CONCERN_INDEX'),
    ('Ideology (liberal higher)', 'IDEOLOGY'),
    ('Conservative (1 lib – 5 cons)', 'CONSERVATIVE'),
    ('Concern × Conservative', 'CONCERN_x_CONSERV'),
    ('Age Category', 'AGE_CAT'),
    ('Female', 'FEMALE'),
    ('College Graduate', 'COLLEGE'),
    ('Income Tier', 'INCOME_TIER'),
    ('White Non-Hispanic', 'WHITE'),
]
a2_footer = [
    ('N', [f"{int(m.nobs):,}" for m in a2_models]),
    ('Log-Likelihood', [f"{m.llf:.1f}" for m in a2_models]),
]

table_a2 = build_combined_table(a2_models, a2_columns, a2_var_order, a2_footer)
print(table_a2.to_string(index=False))
print()
print("Note: * p < 0.10, ** p < 0.05, *** p < 0.01.")
print("Standard errors in parentheses. Models do not apply survey weights.")
print("Threshold parameters omitted from this display.")
print()


# ============================================================
# TABLE A.3: Unweighted OLS with HC1 SEs
# ============================================================
print("=" * 100)
print("TABLE A.3: Unweighted OLS Regression Results")
print("=" * 100)

a3_models = [m1_h1_ols, m2_h1_ols, m1_h2_ols, m2_h2_ols, m_h3a_ols, m_h3b_ols]
a3_columns = ['H1 M1', 'H1 M2', 'H2 M1', 'H2 M2', 'H3a', 'H3b']
a3_var_order = a1_var_order  # same variable order as A.1
a3_footer = [
    ('N', [f"{int(m.nobs):,}" for m in a3_models]),
    ('R²', [f"{m.rsquared:.3f}" for m in a3_models]),
]

table_a3 = build_combined_table(a3_models, a3_columns, a3_var_order, a3_footer)
print(table_a3.to_string(index=False))
print()
print("Note: * p < 0.10, ** p < 0.05, *** p < 0.01.")
print("HC1 robust standard errors in parentheses.")
print("Models do not apply Pew ATP survey weights.")
print()


# ============================================================
# TABLE A.4: Sample Demographics by Ideology
# ============================================================
print("=" * 100)
print("TABLE A.4: Sample Demographics by Ideology")
print("=" * 100)

demo = df[['IDEOLOGY', 'AGE_CAT', 'FEMALE', 'COLLEGE',
           'INCOME_TIER', 'WHITE', 'WT']].dropna()
demo['group'] = pd.cut(demo['IDEOLOGY'], bins=[0, 2, 3, 5],
                       labels=['Conservative', 'Moderate', 'Liberal'])


def wmean(x, w):
    return (x * w).sum() / w.sum()


a4_rows = []
for g in ['Conservative', 'Moderate', 'Liberal']:
    sub = demo[demo['group'] == g]
    w = sub['WT']
    a4_rows.append({
        'Group': g,
        'N': f"{len(sub):,}",
        'Age (mean)': f"{wmean(sub['AGE_CAT'], w):.3f}",
        'Female (%)': f"{wmean(sub['FEMALE'], w) * 100:.3f}",
        'College (%)': f"{wmean(sub['COLLEGE'], w) * 100:.3f}",
        'Income (mean)': f"{wmean(sub['INCOME_TIER'], w):.3f}",
        'White (%)': f"{wmean(sub['WHITE'], w) * 100:.3f}",
    })

table_a4 = pd.DataFrame(a4_rows)
print(table_a4.to_string(index=False))
print()


# ============================================================
# TABLE A.5: AI Concern Index Item Statistics
# ============================================================
print("=" * 100)
print("TABLE A.5: AI Concern Index Item Statistics")
print("=" * 100)

items = [c + '_r' for c in concern_items]
item_df = df[items].dropna()
total = item_df.sum(axis=1)

item_labels = {
    'AICONCERN_a_W152_r': 'AICONCERN_a (bias in AI decisions)',
    'AICONCERN_b_W152_r': 'AICONCERN_b (AI used to impersonate people)',
    'AICONCERN_c_W152_r': 'AICONCERN_c (personal information misused by AI)',
    'AICONCERN_d_W152_r': 'AICONCERN_d (inaccurate information from AI)',
    'AICONCERN_e_W152_r': 'AICONCERN_e (people not understanding AI)',
    'AICONCERN_f_W152_r': 'AICONCERN_f (less human connection due to AI)',
    'AICONCERN_g_W152_r': 'AICONCERN_g (AI leading to job loss)',
}

a5_rows = []
for col in items:
    # item-total correlation: correlate item with sum of OTHER items
    others = total - item_df[col]
    corr = np.corrcoef(item_df[col], others)[0, 1]
    a5_rows.append({
        'Item': item_labels.get(col, col),
        'Mean': f"{item_df[col].mean():.3f}",
        'SD': f"{item_df[col].std():.3f}",
        'Item-Total Correlation': f"{corr:.3f}",
    })

table_a5 = pd.DataFrame(a5_rows)
print(table_a5.to_string(index=False))
print()


# ============================================================
# OPTIONAL: Export all tables to a single Excel file
# ============================================================
EXPORT_TO_EXCEL = True

if EXPORT_TO_EXCEL:
    with pd.ExcelWriter('appendix_tables_consolidated.xlsx', engine='openpyxl') as writer:
        table_a1.to_excel(writer, sheet_name='A1_WLS_classic_SEs', index=False)
        table_a2.to_excel(writer, sheet_name='A2_Ordered_Logit', index=False)
        table_a3.to_excel(writer, sheet_name='A3_Unweighted_OLS', index=False)
        table_a4.to_excel(writer, sheet_name='A4_Demographics', index=False)
        table_a5.to_excel(writer, sheet_name='A5_Item_Statistics', index=False)
    print("Exported all tables to: appendix_tables_consolidated.xlsx")

print()
print("Done. Verify the numbers above match the values in the Word document.")

pip install python-docx

"""
Build Consolidated Appendix Tables (python-docx version)
=========================================================

Produces a Word document with all five appendix tables in academic-style
formatting: horizontal rules only (no vertical borders), Times New Roman,
two-row-per-variable layout (coefficient over standard error in italics),
significance stars assigned at conventional thresholds.

Requires:
    pip install python-docx

Usage:
    Run AFTER your existing notebook cells (specifically after Cell 9 which
    creates h1, h2, h3a, h3b dataframes). Either paste this entire script
    into a new notebook cell, or save as a .py file and run it in the same
    Python environment where you ran the notebook.

Assumes the following objects already exist in your namespace:
    df, controls, h1, h2, h3a, h3b, concern_items
"""

import pandas as pd
import numpy as np
import statsmodels.api as sm
from statsmodels.miscmodels.ordinal_model import OrderedModel

from docx import Document
from docx.shared import Pt, Twips, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_ALIGN_VERTICAL
from docx.enum.section import WD_ORIENTATION
from docx.oxml.ns import qn
from docx.oxml import OxmlElement


# ============================================================
# STYLING HELPERS
# ============================================================
# These helpers enforce the academic table look: no vertical borders,
# selective horizontal rules, Times New Roman, custom cell padding.

FONT_NAME = 'Times New Roman'
COEF_SIZE = Pt(9)        # coefficient text
SE_SIZE = Pt(8)          # standard error text (italicized, smaller)
HEADER_SIZE = Pt(9)      # column headers
TITLE_SIZE = Pt(11)      # table title
NOTE_SIZE = Pt(8)        # note underneath table


def set_cell_borders(cell, top=False, bottom=False, left=False, right=False):
    """Set individual cell borders on/off. Defaults to all off."""
    tc_pr = cell._tc.get_or_add_tcPr()
    tc_borders = tc_pr.find(qn('w:tcBorders'))
    if tc_borders is None:
        tc_borders = OxmlElement('w:tcBorders')
        tc_pr.append(tc_borders)
    else:
        # clear existing
        for child in list(tc_borders):
            tc_borders.remove(child)

    for side, on in [('top', top), ('bottom', bottom),
                     ('left', left), ('right', right)]:
        border = OxmlElement(f'w:{side}')
        if on:
            border.set(qn('w:val'), 'single')
            border.set(qn('w:sz'), '4')   # 0.5pt
            border.set(qn('w:color'), '000000')
        else:
            border.set(qn('w:val'), 'nil')
        tc_borders.append(border)


def set_cell_margins(cell, top=40, bottom=40, left=80, right=80):
    """Set internal cell padding in twips (1/20 pt)."""
    tc_pr = cell._tc.get_or_add_tcPr()
    tc_mar = OxmlElement('w:tcMar')

    for side, val in [('top', top), ('bottom', bottom),
                      ('left', left), ('right', right)]:
        mar = OxmlElement(f'w:{side}')
        mar.set(qn('w:w'), str(val))
        mar.set(qn('w:type'), 'dxa')
        tc_mar.append(mar)
    tc_pr.append(tc_mar)


def write_cell(cell, text, *, bold=False, italic=False,
               size=COEF_SIZE, align='left'):
    """Write formatted text into a cell, replacing any default paragraph."""
    cell.text = ''   # clear default
    para = cell.paragraphs[0]

    if align == 'center':
        para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    elif align == 'right':
        para.alignment = WD_ALIGN_PARAGRAPH.RIGHT
    else:
        para.alignment = WD_ALIGN_PARAGRAPH.LEFT

    para.paragraph_format.space_before = Pt(0)
    para.paragraph_format.space_after = Pt(0)

    run = para.add_run(text)
    run.font.name = FONT_NAME
    run.font.size = size
    run.bold = bold
    run.italic = italic
    # Set East Asian font too (some Word versions need this)
    rPr = run._element.get_or_add_rPr()
    rFonts = rPr.find(qn('w:rFonts'))
    if rFonts is None:
        rFonts = OxmlElement('w:rFonts')
        rPr.insert(0, rFonts)
    rFonts.set(qn('w:ascii'), FONT_NAME)
    rFonts.set(qn('w:hAnsi'), FONT_NAME)


def set_table_column_widths(table, widths):
    """Set fixed column widths in twips."""
    for row in table.rows:
        for idx, cell in enumerate(row.cells):
            if idx < len(widths):
                cell.width = Twips(widths[idx])
    # Also set on the gridCol element
    tbl = table._tbl
    grid = tbl.find(qn('w:tblGrid'))
    if grid is not None:
        for child in list(grid):
            grid.remove(child)
        for w in widths:
            gc = OxmlElement('w:gridCol')
            gc.set(qn('w:w'), str(w))
            grid.append(gc)


def add_table_title(doc, text):
    """Add a bold table title above a table."""
    p = doc.add_paragraph()
    p.paragraph_format.space_before = Pt(12)
    p.paragraph_format.space_after = Pt(2)
    run = p.add_run(text)
    run.font.name = FONT_NAME
    run.font.size = TITLE_SIZE
    run.bold = True


def add_table_note(doc, text):
    """Add an italicized note underneath a table."""
    p = doc.add_paragraph()
    p.paragraph_format.space_before = Pt(2)
    p.paragraph_format.space_after = Pt(12)
    run = p.add_run(text)
    run.font.name = FONT_NAME
    run.font.size = NOTE_SIZE
    run.italic = True


# ============================================================
# STATISTICAL HELPERS
# ============================================================
def stars(p):
    if p < 0.01:
        return '***'
    elif p < 0.05:
        return '**'
    elif p < 0.10:
        return '*'
    return ''


def fmt_coef(coef, p):
    return f"{coef:.3f}{stars(p)}"


def fmt_se(se):
    return f"({se:.3f})"


def extract_row(model, var_name):
    """Return (coef_str, se_str) for a variable, or empty strings if not in model."""
    if var_name not in model.params.index:
        return ("", "")
    return (fmt_coef(model.params[var_name], model.pvalues[var_name]),
            fmt_se(model.bse[var_name]))


# ============================================================
# RE-RUN ALL MODELS
# ============================================================
print("Fitting all models...")

# A.1: WLS classic SEs
m1_h1_nr = sm.WLS(h1['AIREG'],
                  sm.add_constant(h1[['AI_CONCERN_INDEX']]),
                  weights=h1['WT']).fit()
m2_h1_nr = sm.WLS(h1['AIREG'],
                  sm.add_constant(h1[['AI_CONCERN_INDEX'] + controls]),
                  weights=h1['WT']).fit()
m1_h2_nr = sm.WLS(h2['REGCONFG'],
                  sm.add_constant(h2[['AI_CONCERN_INDEX']]),
                  weights=h2['WT']).fit()
m2_h2_nr = sm.WLS(h2['REGCONFG'],
                  sm.add_constant(h2[['AI_CONCERN_INDEX'] + controls]),
                  weights=h2['WT']).fit()

h3_vars = ['AI_CONCERN_INDEX', 'CONSERVATIVE', 'CONCERN_x_CONSERV',
           'AGE_CAT', 'FEMALE', 'COLLEGE', 'INCOME_TIER', 'WHITE']
m_h3a_nr = sm.WLS(h3a['AIREG'],
                  sm.add_constant(h3a[h3_vars]),
                  weights=h3a['WT']).fit()
m_h3b_nr = sm.WLS(h3b['REGCONFG'],
                  sm.add_constant(h3b[h3_vars]),
                  weights=h3b['WT']).fit()

# A.2: Ordered Logit
h1_ol = df[['AIREG', 'AI_CONCERN_INDEX'] + controls].dropna()
h2_ol = df[['REGCONFG', 'AI_CONCERN_INDEX'] + controls].dropna()
ologit_h1 = OrderedModel(h1_ol['AIREG'],
                         h1_ol[['AI_CONCERN_INDEX'] + controls],
                         distr='logit').fit(method='bfgs', disp=False)
ologit_h2 = OrderedModel(h2_ol['REGCONFG'],
                         h2_ol[['AI_CONCERN_INDEX'] + controls],
                         distr='logit').fit(method='bfgs', disp=False)

h3a_ol_data = df[['AIREG', 'AI_CONCERN_INDEX', 'CONSERVATIVE',
                  'AGE_CAT', 'FEMALE', 'COLLEGE', 'INCOME_TIER', 'WHITE']].dropna()
h3a_ol_data['CONCERN_x_CONSERV'] = (h3a_ol_data['AI_CONCERN_INDEX']
                                    * h3a_ol_data['CONSERVATIVE'])
ologit_h3a = OrderedModel(h3a_ol_data['AIREG'],
                          h3a_ol_data[h3_vars],
                          distr='logit').fit(method='bfgs', disp=False)

h3b_ol_data = df[['REGCONFG', 'AI_CONCERN_INDEX', 'CONSERVATIVE',
                  'AGE_CAT', 'FEMALE', 'COLLEGE', 'INCOME_TIER', 'WHITE']].dropna()
h3b_ol_data['CONCERN_x_CONSERV'] = (h3b_ol_data['AI_CONCERN_INDEX']
                                    * h3b_ol_data['CONSERVATIVE'])
ologit_h3b = OrderedModel(h3b_ol_data['REGCONFG'],
                          h3b_ol_data[h3_vars],
                          distr='logit').fit(method='bfgs', disp=False)

# A.3: Unweighted OLS HC1
m1_h1_ols = sm.OLS(h1['AIREG'],
                   sm.add_constant(h1[['AI_CONCERN_INDEX']])
                   ).fit(cov_type='HC1')
m2_h1_ols = sm.OLS(h1['AIREG'],
                   sm.add_constant(h1[['AI_CONCERN_INDEX'] + controls])
                   ).fit(cov_type='HC1')
m1_h2_ols = sm.OLS(h2['REGCONFG'],
                   sm.add_constant(h2[['AI_CONCERN_INDEX']])
                   ).fit(cov_type='HC1')
m2_h2_ols = sm.OLS(h2['REGCONFG'],
                   sm.add_constant(h2[['AI_CONCERN_INDEX'] + controls])
                   ).fit(cov_type='HC1')
m_h3a_ols = sm.OLS(h3a['AIREG'],
                   sm.add_constant(h3a[h3_vars])
                   ).fit(cov_type='HC1')
m_h3b_ols = sm.OLS(h3b['REGCONFG'],
                   sm.add_constant(h3b[h3_vars])
                   ).fit(cov_type='HC1')

print("All models fitted.")


# ============================================================
# TABLE BUILDERS
# ============================================================

def build_regression_table(doc, title, columns, subheader, var_order,
                           models, footer_rows, total_width=14400):
    """
    Build a regression table with:
    - title row (with top + bottom border)
    - column header row
    - subheader row (DV labels, italic)
    - bottom border under headers
    - one row pair (coef + SE) per variable
    - top border above footer
    - bottom border at end
    """
    add_table_title(doc, title)

    n_cols = len(columns)
    label_width = int(total_width * 0.28)
    data_width = (total_width - label_width) // (n_cols - 1)
    col_widths = [label_width] + [data_width] * (n_cols - 1)

    # Total rows: 1 header + 1 subheader + 2 per variable + footer rows
    n_var_rows = len(var_order) * 2
    n_footer = len(footer_rows)
    total_rows = 1 + 1 + n_var_rows + n_footer

    table = doc.add_table(rows=total_rows, cols=n_cols)
    table.autofit = False

    # All cells start with no borders, no padding
    for row in table.rows:
        for cell in row.cells:
            set_cell_borders(cell)
            set_cell_margins(cell)

    set_table_column_widths(table, col_widths)

    # Row 0: Column headers (top + bottom border on this row)
    for i, col_label in enumerate(columns):
        cell = table.rows[0].cells[i]
        align = 'left' if i == 0 else 'center'
        write_cell(cell, col_label, bold=True, size=HEADER_SIZE, align=align)
        set_cell_borders(cell, top=True, bottom=True)

    # Row 1: Subheader (DV labels), italicized
    for i, sub_label in enumerate(subheader):
        cell = table.rows[1].cells[i]
        align = 'left' if i == 0 else 'center'
        write_cell(cell, sub_label, italic=True, size=SE_SIZE, align=align)

    # Variable rows (2 per variable)
    row_idx = 2
    for display_name, internal_name in var_order:
        # Coefficient row
        write_cell(table.rows[row_idx].cells[0], display_name,
                   size=COEF_SIZE, align='left')
        for i, m in enumerate(models, start=1):
            coef_str, _ = extract_row(m, internal_name)
            write_cell(table.rows[row_idx].cells[i], coef_str,
                       size=COEF_SIZE, align='center')
        # SE row
        write_cell(table.rows[row_idx + 1].cells[0], '',
                   size=COEF_SIZE, align='left')
        for i, m in enumerate(models, start=1):
            _, se_str = extract_row(m, internal_name)
            write_cell(table.rows[row_idx + 1].cells[i], se_str,
                       italic=True, size=SE_SIZE, align='center')
        row_idx += 2

    # Footer rows
    for f_idx, (label, values) in enumerate(footer_rows):
        is_first = f_idx == 0
        is_last = f_idx == len(footer_rows) - 1

        cells = table.rows[row_idx].cells
        write_cell(cells[0], label, size=COEF_SIZE, align='left')
        if is_first:
            set_cell_borders(cells[0], top=True)
        if is_last:
            set_cell_borders(cells[0], bottom=True,
                             top=is_first)

        for i, v in enumerate(values, start=1):
            write_cell(cells[i], v, size=COEF_SIZE, align='center')
            if is_first:
                set_cell_borders(cells[i], top=True)
            if is_last:
                set_cell_borders(cells[i], bottom=True,
                                 top=is_first)
        row_idx += 1

    return table


def build_simple_table(doc, title, rows, total_width=14400):
    """Build a simple table where row[0] is the header row."""
    add_table_title(doc, title)

    n_cols = len(rows[0])
    col_width = total_width // n_cols
    col_widths = [col_width] * n_cols

    table = doc.add_table(rows=len(rows), cols=n_cols)
    table.autofit = False

    for row in table.rows:
        for cell in row.cells:
            set_cell_borders(cell)
            set_cell_margins(cell)

    set_table_column_widths(table, col_widths)

    for r_idx, row_data in enumerate(rows):
        is_header = r_idx == 0
        is_last = r_idx == len(rows) - 1
        for c_idx, val in enumerate(row_data):
            cell = table.rows[r_idx].cells[c_idx]
            align = 'left' if c_idx == 0 else 'center'
            write_cell(cell, str(val), bold=is_header,
                       size=COEF_SIZE, align=align)
            if is_header:
                set_cell_borders(cell, top=True, bottom=True)
            if is_last:
                set_cell_borders(cell, bottom=True)
    return table


# ============================================================
# CREATE THE DOCUMENT
# ============================================================
doc = Document()

# Set landscape, US Letter, 0.5" margins
section = doc.sections[0]
section.orientation = WD_ORIENTATION.LANDSCAPE
section.page_width = Twips(15840)   # 11"
section.page_height = Twips(12240)  # 8.5"
section.top_margin = Twips(1080)    # 0.75"
section.bottom_margin = Twips(1080)
section.left_margin = Twips(720)    # 0.5"
section.right_margin = Twips(720)

# Set default style
styles = doc.styles
normal = styles['Normal']
normal.font.name = FONT_NAME
normal.font.size = Pt(11)

# Title
title_para = doc.add_paragraph()
title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
title_run = title_para.add_run('Appendix')
title_run.font.name = FONT_NAME
title_run.font.size = Pt(16)
title_run.bold = True

# Variable order shared across A.1 and A.3
shared_var_order = [
    ('AI Concern Index', 'AI_CONCERN_INDEX'),
    ('Ideology (liberal higher)', 'IDEOLOGY'),
    ('Conservative (1 lib – 5 cons)', 'CONSERVATIVE'),
    ('Concern × Conservative', 'CONCERN_x_CONSERV'),
    ('Age Category', 'AGE_CAT'),
    ('Female', 'FEMALE'),
    ('College Graduate', 'COLLEGE'),
    ('Income Tier', 'INCOME_TIER'),
    ('White Non-Hispanic', 'WHITE'),
    ('Constant', 'const'),
]

# ----------------- TABLE A.1 -----------------
a1_models = [m1_h1_nr, m2_h1_nr, m1_h2_nr, m2_h2_nr, m_h3a_nr, m_h3b_nr]
a1_columns = ['', 'H1 M1', 'H1 M2', 'H2 M1', 'H2 M2', 'H3a', 'H3b']
a1_subheader = ['', 'AIREG', 'AIREG', 'REGCONFG', 'REGCONFG', 'AIREG', 'REGCONFG']
a1_footer = [
    ('N', [f"{int(m.nobs):,}" for m in a1_models]),
    ('R²', [f"{m.rsquared:.3f}" for m in a1_models]),
]
build_regression_table(doc,
                       'Table A.1. WLS with Classic (Non-Robust) Standard Errors',
                       a1_columns, a1_subheader, shared_var_order,
                       a1_models, a1_footer)
add_table_note(doc,
               'Note: * p < 0.10, ** p < 0.05, *** p < 0.01. Classic '
               '(non-robust) standard errors in parentheses. All models apply '
               'Pew ATP Wave 152 survey weights. Columns H1 M1 and H2 M1 report '
               'bivariate models; H1 M2 and H2 M2 add demographic controls and '
               'ideology; H3a and H3b add the Concern × Conservative interaction '
               'term in place of ideology.')

# ----------------- TABLE A.2 -----------------
a2_models = [ologit_h1, ologit_h2, ologit_h3a, ologit_h3b]
a2_columns = ['', 'H1', 'H2', 'H3a', 'H3b']
a2_subheader = ['', 'AIREG', 'REGCONFG', 'AIREG', 'REGCONFG']
a2_var_order = [
    ('AI Concern Index', 'AI_CONCERN_INDEX'),
    ('Ideology (liberal higher)', 'IDEOLOGY'),
    ('Conservative (1 lib – 5 cons)', 'CONSERVATIVE'),
    ('Concern × Conservative', 'CONCERN_x_CONSERV'),
    ('Age Category', 'AGE_CAT'),
    ('Female', 'FEMALE'),
    ('College Graduate', 'COLLEGE'),
    ('Income Tier', 'INCOME_TIER'),
    ('White Non-Hispanic', 'WHITE'),
]
a2_footer = [
    ('N', [f"{int(m.nobs):,}" for m in a2_models]),
    ('Log-Likelihood', [f"{m.llf:.1f}" for m in a2_models]),
]
build_regression_table(doc,
                       'Table A.2. Full Ordered Logit Results',
                       a2_columns, a2_subheader, a2_var_order,
                       a2_models, a2_footer)
add_table_note(doc,
               'Note: * p < 0.10, ** p < 0.05, *** p < 0.01. Standard errors in '
               'parentheses. Ordered logistic regression models estimated with '
               'the BFGS optimizer. Models do not apply survey weights. '
               'Threshold parameters omitted from this display.')

# ----------------- TABLE A.3 -----------------
a3_models = [m1_h1_ols, m2_h1_ols, m1_h2_ols, m2_h2_ols, m_h3a_ols, m_h3b_ols]
a3_footer = [
    ('N', [f"{int(m.nobs):,}" for m in a3_models]),
    ('R²', [f"{m.rsquared:.3f}" for m in a3_models]),
]
build_regression_table(doc,
                       'Table A.3. Unweighted OLS Regression Results',
                       a1_columns, a1_subheader, shared_var_order,
                       a3_models, a3_footer)
add_table_note(doc,
               'Note: * p < 0.10, ** p < 0.05, *** p < 0.01. HC1 robust '
               'standard errors in parentheses. Models do not apply Pew ATP '
               'survey weights, in contrast to the WLS models in the main text.')

# ----------------- TABLE A.4: Sample Demographics -----------------
demo = df[['IDEOLOGY', 'AGE_CAT', 'FEMALE', 'COLLEGE',
           'INCOME_TIER', 'WHITE', 'WT']].dropna()
demo['group'] = pd.cut(demo['IDEOLOGY'], bins=[0, 2, 3, 5],
                       labels=['Conservative', 'Moderate', 'Liberal'])


def wmean(x, w):
    return (x * w).sum() / w.sum()


a4_rows = [['Group', 'N', 'Age (mean)', 'Female (%)', 'College (%)',
            'Income (mean)', 'White (%)']]
for g in ['Conservative', 'Moderate', 'Liberal']:
    sub = demo[demo['group'] == g]
    w = sub['WT']
    a4_rows.append([
        g,
        f"{len(sub):,}",
        f"{wmean(sub['AGE_CAT'], w):.3f}",
        f"{wmean(sub['FEMALE'], w) * 100:.3f}",
        f"{wmean(sub['COLLEGE'], w) * 100:.3f}",
        f"{wmean(sub['INCOME_TIER'], w):.3f}",
        f"{wmean(sub['WHITE'], w) * 100:.3f}",
    ])

build_simple_table(doc, 'Table A.4. Sample Demographics by Ideology', a4_rows)
add_table_note(doc,
               'Note: Weighted means and percentages by ideology group, using '
               'Pew ATP Wave 152 survey weights. Conservative includes very '
               'conservative and conservative; Moderate includes only moderate; '
               'Liberal includes liberal and very liberal.')

# ----------------- TABLE A.5: Item Statistics -----------------
items = [c + '_r' for c in concern_items]
item_df = df[items].dropna()
total = item_df.sum(axis=1)

item_labels = {
    'AICONCERN_a_W152_r': 'AICONCERN_a (bias in AI decisions)',
    'AICONCERN_b_W152_r': 'AICONCERN_b (AI used to impersonate people)',
    'AICONCERN_c_W152_r': 'AICONCERN_c (personal information misused by AI)',
    'AICONCERN_d_W152_r': 'AICONCERN_d (inaccurate information from AI)',
    'AICONCERN_e_W152_r': 'AICONCERN_e (people not understanding AI)',
    'AICONCERN_f_W152_r': 'AICONCERN_f (less human connection due to AI)',
    'AICONCERN_g_W152_r': 'AICONCERN_g (AI leading to job loss)',
}

a5_rows = [['Item', 'Mean', 'SD', 'Item-Total Correlation']]
for col in items:
    others = total - item_df[col]
    corr = np.corrcoef(item_df[col], others)[0, 1]
    a5_rows.append([
        item_labels.get(col, col),
        f"{item_df[col].mean():.3f}",
        f"{item_df[col].std():.3f}",
        f"{corr:.3f}",
    ])

build_simple_table(doc, 'Table A.5. AI Concern Index Item Statistics', a5_rows)
add_table_note(doc,
               'Note: Statistics for the seven items composing the AI Concern '
               'Index. Each item asks how concerned respondents are about a '
               'specific AI-related issue, on a five-point scale (1 = Not at '
               'all concerned, 5 = Extremely concerned). Item-total correlations '
               'are correlations between each item and the sum of the remaining '
               'six items. Cronbach\u2019s alpha for the seven-item index is 0.86.')

# Save
output_filename = 'appendix_consolidated_python.docx'
doc.save(output_filename)
print(f"\nDocument saved: {output_filename}")
print("Open in Word to verify formatting matches the JavaScript-generated version.")